# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Tryston Minsquero
email: Trystonminsquero@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Tryson Minsquero's personal website.

url: http://www.trystonminsquero.com # the base hostname & protocol of the site

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: _pages
    values:
      layout: default
  - scope:
      path: _posts
    values:
      layout: post

collections:
  posts:
    permalink: /posts/:title/

include: ["_pages", "_redirects", "assets/css"]
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

# Compress.html (html minifier)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]